version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: xss-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xss_lab
      MYSQL_USER: xss_user
      MYSQL_PASSWORD: xss_pass
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
